### ISSUE TITLE
How to configure ciphering and integrity algorithm for UE?

### ISSUE THREAD

**Issue by LucasCSTI** [mitshell/corenet#10]
How to configure ciphering and integrity algorithm for UE (corenet-46666: [corenet-46666.zip](https://github.com/mitshell/corenet/files/3873977/corenet-46666.zip))?

Currently I only see EEA0 and EIA1 in SMC messages. (pcap file form S1AP: [corenet_S1AP_20191121v2.zip](https://github.com/mitshell/corenet/files/3873985/corenet_S1AP_20191121v2.zip))

![corenet_S1AP_EEA0 EIA1_20191121v2](https://user-images.githubusercontent.com/57480163/69326163-4fab5180-0c86-11ea-9fa5-fdc9f64799a8.png)

How to allow UE conneting to internet? Currently I only see GTPU traffic from eNB side and no return traffic.

![corenet_S1AP_20191121v2](https://user-images.githubusercontent.com/57480163/69326301-841f0d80-0c86-11ea-99e5-eda2fbd2ef67.png)

**Comment by mitshell** [comment]
Regarding the NAS security algorithm config, I added this:
https://github.com/mitshell/corenet/blob/f63e5cfc390e9ec83c98529db0337c0ca3114e31/corenet.py#L320

Regarding Internet connectivity, I cannot help. This is up to you to setup the proper configuration and route in your network and in corenet.py file, and to do a proper analysis of what uplink / downlink traffic goes where.

**Comment by LucasCSTI** [comment]
Thanks.
