### ISSUE TITLE
Replace libmich with pycrate 

### ISSUE THREAD

**Issue by smarek** [mitshell/corenet#3]
Hi,

https://github.com/mitshell/libmich README states that development has been stopped in favor of https://github.com/anssi-fr/pycrate which is meant to replace libmich. Alo pycrate support both Python 2 and Python 3

Do you plan to switch from libmich to pycrate, or is it ill idea?

Thank you

**Comment by mitshell** [comment]
That is the plan. When pycrate will be ready to support the whole 4G core network part, I will update corenet to use it.
