### ISSUE TITLE
IP address 

### ISSUE THREAD

**Issue by HacKeD0x90** [mitshell/corenet#4]
Hello I'm getting an error that it couldn't bind port to address 10.1.1.1, so i edited the ip address in the file to my ip address, but after that i got another error that it couldn't bind port to ip address 10.2.2.2.

is it required to have multiple ip addresses or how should i setup the environment.?

**Comment by mitshell** [comment]
You need to configure CorenetServer.SERVER_HNB and CorenetServer.SERVER_ENB to bind on an existing interface / IP address of your machine.
Both services (HNB / ENB) can bind on the same IP address in case your HomeNodeB / eNodeB are on the same LAN.
