### ISSUE TITLE
Issue in attaching 

### ISSUE THREAD

**Issue by akibsayyed** [mitshell/corenet#5]
I am using corenet EPC. I am getting mac failure (20)

here is log from  corenet.log
https://pastebin.com/YpLsDQi7
here auc.db
https://pastebin.com/vJhMCgps

here is pcap 

[mac_failure2.pcapng.zip](https://github.com/mitshell/corenet/files/2188628/mac_failure2.pcapng.zip)

Please guide me where exactly is error

**Comment by mitshell** [comment]
This means the authentication data stored in the network does not correspond to what is stored in the USIM. This can come from incorrect Ki or SQN values in the AuC.db file, or an incorrect AuC.OP value in the corenet.py file. 

You should probably reprogram your USIM to resynchronize those 3 parameters correctly with your network config.
