### ISSUE TITLE
How to trigger attach procedure using corenet.py

### ISSUE THREAD

**Issue by Hanumantappa** [mitshell/corenet#6]
Hi,  I am planning to use corenet.py for corenetwork and UE functionality to test my enodb.  I see after attach data is being pasted.  But not specified how to trigger attach procedure,  i am able to see S1-setup success with my Enodb,  but Attach not triggered.  Could you help me how to trigger attach procedure.

**Comment by Hanumantappa** [comment]
I am using only ENODEB and not configured HNB, also i need only control plan messages..so didn't configure GTPU also.

**Comment by mitshell** [comment]
Attach is initiated by the UE (the handset) only, there is no way to initiate an Attach from the core network side. So, you have to use a handset to connect to your eNodeB and then to corenet: this will trigger an attach procedure.
