### ISSUE TITLE
Disable Encryption and attach IMSI by regex?

### ISSUE THREAD

**Issue by BorjanEch0** [mitshell/corenet#7]
Hi Dear Developer,

I would like to kindly ask if your software can support the following features for testing and development purposes?

**Comment by mitshell** [comment]
Sure !
For filtering IMSI, read here: https://github.com/mitshell/corenet/blob/master/corenet.py#L297

For configuring the NAS security algorithms, the setting is here:
https://github.com/P1sec/pycrate/blob/master/pycrate_corenet/HdlrUES1.py#L160
You can add such a line in corenet.py, that will disable NAS encryption (this is however already the default config in corenet):
UEEMMd.SMC_EEA_PRIO = [0]

For the AS (radio) security algorithms, the setting has to be done in your eNodeB.

**Comment by BorjanEch0** [comment]
Ah! so kind of you! thank you for the reply and info.
