### ISSUE TITLE
hNodeB no signal is being transmitted, but SCTP connection is successful 

### ISSUE THREAD

**Issue by BorjanEch0** [mitshell/corenet#9]
HI!
My hNodeB is connecting to corenet but refuses to give signal, LTE Works on the same multimode BTS also via corenet, but UMTS fails to produce signal at PA output, hardware and hNodeB config is confirmed correct by Spectrum Analyzer confirming Broadcast of test signal from PA at boot time signaling BOOT OK. What should i attach for detailed help?

Kind thanks.

**Comment by mitshell** [comment]
Did you configure the corenet SERVER_HNB parameters properly, according to your network config ? See https://github.com/mitshell/corenet/blob/2fc9876220b26114bdbffa9a00ef22fd699e77af/corenet.py#L67.
Did you configure your Home-NodeB with those corenet IP and port ?

From here, please provide a network capture of the corenet SERVER_HNB interface ; without this, I cannot help.

**Comment by BorjanEch0** [comment]
That Configuration parameter is correct and the hNodeB connects to corenet successfully if SCTP socket fails the hNodeB raises Critical error SCTP Link broken which is not the case here, i will start the corenet, start packet capture, boot the HNB while capturing, verify successful LTE network and then stop capture and upload the file, thank you very much!

**Comment by BorjanEch0** [comment]
Here is pcap between hnb and corenet,
[hnb.zip](https://github.com/mitshell/corenet/files/3513158/hnb.zip)

Thank you

**Comment by BorjanEch0** [comment]
Was the pcap of any help or should i attach more files?
Thank you!

**Comment by mitshell** [comment]
Thanks for the capture. I guess that your corenet server is listening on IP 10.0.0.2, and that there is an LTE eNodeB at 10.0.0.5 (which does an S1Setup properly). There are 2 others IP doing SCTP signalling traffic with 10.0.0.2:
- 10.0.0.7 which sends unknown data on port SCTP/14597
- 10.0.0.8 which sends NBAP Reset and AuditRequiredIndication messages
Corenet / pycrate do not support any proprietary protocols, neither NBAP (which is the protocol between a 3G NodeB and RNC, not for 3G femtocell but for 3G macrocell).

Could you please indicate the type and model of 3G femtocell that you are trying to use as hNodeB ?

**Comment by BorjanEch0** [comment]
Thank you very much for your kind support!!

Yes the server IP is 10.0.0.2,
There is a multimode macrocell holding IPS as follows:

10.0.0.5 LTE SCTP port 36412
10.0.0.7 ABIS over SCTP for GSM port 14597
10.0.0.8 RNC IuB SCTP Port 29169
and i can confirm that the site in question is a full scale, multimode(GSM,UMTS,LTE) macrocell.

What options do i have in this case?

**Comment by mitshell** [comment]
corenet does not support GSM / GPRS, hence no support for Abis. Maybe OpenBSC from osmocom can support such Abis interface, however I am not sure it supports Abis over SCTP: this has to be checked with the people at osmocom / sysmocom.
Similarly, corenet does not support the Iub interface ; and I am not aware of any open-source software supporting it (or more largely emulating a 3G RNC) : so no clear options for you, here.

I would be curious to know which equipment do you use: do not hesitate to send me more information about it (by email, in case you don't want to put it on github).

**Comment by BorjanEch0** [comment]
Yes i understand, the GSM connection goes to another program on the same machine. I am already cooperating with them on the mater of implementing SCTP support, i am also aware of that. i will now close this issue, please send me your email, we can continue the conversation about my setup and intentions there. Thank you!

**Comment by mitshell** [comment]
michau.benoit@gmail.com
